research_task:
 description: >
  Use the following memories (user and assistant) to assist with answering the user query if relevant


  {memories}


  After, infer what {topic} means in context of the conversation with the memories you've been given.
  Than research the {topic} using only relevant history to make sure your memories are up to date

 expected_output: >
   A general summary with no sensitive data, ensuring relevance to the topic
 agent: researcher

reporting_task:
 description: >
   Use the following memories to assist with answering the user query if relevant - {memories}
   If not, summarize research findings in bullet points, focusing on clarity, accuracy, and compliance.
 expected_output: >
   Bullet points summarizing the topic.
 agent: reporting_analyst

support_task:
 description: >
   Perform a final review of the summary for compliance and accuracy, 
   ensuring it follows privacy guidelines.
 expected_output: >
   Finalized compliant summary that was given from the summarizer agent 
 agent: support_QA_agent
